import pytest
from superctx.guard import classify_write_path

def test_classify_write_path():
    tracked = {"CLAUDE.md", "AGENTS.md"}
    # 1. Ignored paths
    assert classify_write_path(".git/config", tracked) == "ignored_hidden_path"
    assert classify_write_path("src/.venv/bin/pytest", tracked) == "ignored_hidden_path"
    # 2. Tracked shim
    assert classify_write_path("CLAUDE.md", tracked) == "known_generated_shim"
    # 3. Known instruction file (untracked)
    assert classify_write_path("GEMINI.md", tracked) == "known_instruction_file"
    # 4. Agent folder candidates
    assert classify_write_path(".claude/settings.json", tracked) == "known_agent_folder_file"
    # 5. Unknown hidden
    assert classify_write_path(".other-tool/config", tracked) == "unknown_hidden_path"
    # 6. Normal file
    assert classify_write_path("src/main.py", tracked) == "normal_file"


def test_pre_tool_use_candidate_repo(tmp_path, monkeypatch):
    import json
    from superctx.guard import handle_pre_tool_use
    # Create candidate files but no .ctx
    (tmp_path / ".claude").mkdir()
    (tmp_path / ".claude" / "CLAUDE.md").write_text("orig", encoding="utf-8")

    payload = {
        "cwd": str(tmp_path),
        "tool_name": "Write",
        "tool_input": {
            "file_path": str(tmp_path / "CLAUDE.md")
        }
    }
    code, msg = handle_pre_tool_use(payload)
    assert code == 2
    assert "I found existing agent instruction files" in msg


def test_pre_tool_use_managed_healthy(tmp_path):
    from superctx.guard import handle_pre_tool_use
    # Initialize managed healthy repo
    ctx = tmp_path / ".ctx"
    ctx.mkdir()
    (ctx / "manifest.toml").write_text('[project]\nname="test"\nhub=".ctx/SUPERCTX.md"\n[[files]]\npath="CLAUDE.md"\nbackup_required=true\n', encoding="utf-8")
    (ctx / "SUPERCTX.md").write_text("hub content", encoding="utf-8")

    # Create the backup file
    (ctx / "sources").mkdir()
    (ctx / "sources" / "CLAUDE.md").write_text("original content", encoding="utf-8")

    # Create a valid shim file
    shim_content = "<!-- Generated by SuperCtx [DO NOT EDIT] -->\nUse .ctx/SUPERCTX.md"
    (tmp_path / "CLAUDE.md").write_text(shim_content, encoding="utf-8")

    payload = {
        "cwd": str(tmp_path),
        "tool_name": "Edit",
        "tool_input": {
            "file_path": str(tmp_path / "CLAUDE.md")
        }
    }
    code, msg = handle_pre_tool_use(payload)
    assert code == 2
    assert "is a generated SuperCtx shim" in msg


def test_pre_tool_use_managed_needs_repair_explains_consent_flow(tmp_path):
    from superctx.guard import handle_pre_tool_use

    ctx = tmp_path / ".ctx"
    ctx.mkdir()
    (ctx / "manifest.toml").write_text(
        '[[files]]\npath="CLAUDE.md"\ntools=["Claude"]\n',
        encoding="utf-8",
    )
    (ctx / "SUPERCTX.md").write_text("hub content", encoding="utf-8")
    (ctx / "sources").mkdir()
    (ctx / "sources" / "CLAUDE.md").write_text("original content", encoding="utf-8")

    code, msg = handle_pre_tool_use({
        "cwd": str(tmp_path),
        "tool_name": "Write",
        "tool_input": {"file_path": str(tmp_path / "CLAUDE.md")},
    })

    assert code == 2
    assert "generated shims are broken or missing" in msg
    assert "Proceed with repair?" in msg


def test_pre_tool_use_managed_legacy_explains_consent_flow(tmp_path):
    from superctx.guard import handle_pre_tool_use

    ctx = tmp_path / ".ctx"
    ctx.mkdir()
    (ctx / "manifest.toml").write_text(
        '[[files]]\npath="CLAUDE.md"\ntools=["Claude"]\n',
        encoding="utf-8",
    )
    (ctx / "SUPERCTX.md").write_text("hub content", encoding="utf-8")
    (tmp_path / "CLAUDE.md").write_text("legacy instructions", encoding="utf-8")

    code, msg = handle_pre_tool_use({
        "cwd": str(tmp_path),
        "tool_name": "Edit",
        "tool_input": {"file_path": str(tmp_path / "CLAUDE.md")},
    })

    assert code == 2
    assert "older legacy setup" in msg
    assert "preserving your existing instruction contents" in msg
    assert "Proceed with migration?" in msg


def test_pre_tool_use_not_candidate_explains_setup_mutations(tmp_path):
    from superctx.guard import handle_pre_tool_use

    code, msg = handle_pre_tool_use({
        "cwd": str(tmp_path),
        "tool_name": "Write",
        "tool_input": {"file_path": str(tmp_path / "CLAUDE.md")},
    })

    assert code == 2
    assert "create `.ctx/SUPERCTX.md`" in msg
    assert "back up the original instruction files under `.ctx/sources/`" in msg
    assert "replace the live instruction files with generated shims" in msg
    assert "Proceed with SuperCtx setup instead?" in msg



def test_user_prompt_expansion_init():
    from superctx.guard import handle_user_prompt_expansion
    payload = {"user_prompt": "/init"}
    code, msg = handle_user_prompt_expansion(payload)
    assert code == 2
    assert "create `.ctx/SUPERCTX.md`" in msg
    assert "back up the original instruction files under `.ctx/sources/`" in msg
    assert "replace the live instruction files with generated shims" in msg
    assert "Proceed with SuperCtx setup instead?" in msg


def test_executable_pre_tool_use(tmp_path):
    import os
    import subprocess
    import json
    from pathlib import Path

    hook_script = Path(__file__).parent.parent / "hooks" / "pre-tool-use"

    payload = {
        "cwd": str(tmp_path),
        "tool_name": "Write",
        "tool_input": {
            "file_path": str(tmp_path / "CLAUDE.md")
        }
    }

    env = os.environ.copy()
    env["CLAUDE_PLUGIN_ROOT"] = str(Path(__file__).parent.parent)

    proc = subprocess.run(
        [str(hook_script)],
        input=json.dumps(payload),
        text=True,
        capture_output=True,
        env=env
    )
    assert proc.returncode == 2
    assert "Proceed with SuperCtx setup instead?" in proc.stderr
