from pathlib import Path
import pytest
from superctx import core, registry
from superctx.shim import is_shim, is_shim_file, generate_shim, apply_shim

def make_repo(tmp_path: Path, files: dict[str, str]) -> Path:
    for rel, content in files.items():
        path = tmp_path / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return tmp_path

def test_is_shim():
    assert is_shim("# SuperCtx\n<!-- Generated by SuperCtx [DO NOT EDIT] -->\n@.ctx/SUPERCTX.md\n") is True
    assert is_shim("# SuperCtx\n<!-- Generated by SuperCtx [DO NOT EDIT] -->\nUse the shared project context in `.ctx/SUPERCTX.md`.\n") is True
    assert is_shim("some other text") is False
    assert is_shim("# SuperCtx\nbut no warning marker") is False
    assert is_shim("<!-- Generated by SuperCtx [DO NOT EDIT] --> but no SUPERCTX.md") is False

def test_shim_redirects_edits_to_hub():
    # Generated shims must tell the agent where to write instead of only forbidding edits.
    root_shim = generate_shim("CLAUDE.md", "claude-at-import")
    assert "Edit `.ctx/SUPERCTX.md` instead." in root_shim

    plain_shim = generate_shim("AGENTS.md", "plain-pointer")
    assert "Edit `.ctx/SUPERCTX.md` instead." in plain_shim

    # Nested shims must redirect using a path relative to the shim's own location,
    # matching the import target.
    nested_shim = generate_shim(".codex/AGENTS.md", "plain-pointer")
    assert "Edit `../.ctx/SUPERCTX.md` instead." in nested_shim

    nested_claude = generate_shim(".claude/CLAUDE.md", "claude-at-import")
    assert "Edit `../.ctx/SUPERCTX.md` instead." in nested_claude

def test_is_shim_accepts_legacy_marker():
    # Old shims written before the redirect wording must still be detected as shims,
    # so sync does not treat them as broken and clobber backups.
    legacy = "# SuperCtx\n<!-- Generated by SuperCtx [DO NOT EDIT] -->\n@.ctx/SUPERCTX.md\n"
    assert is_shim(legacy) is True


def test_has_current_policy_is_path_aware():
    from superctx.shim import has_current_policy

    # A freshly generated shim is current for its own path.
    root = generate_shim("CLAUDE.md", "claude-at-import")
    assert has_current_policy(root, "CLAUDE.md") is True

    nested = generate_shim(".claude/CLAUDE.md", "claude-at-import")
    assert has_current_policy(nested, ".claude/CLAUDE.md") is True

    # A nested shim carrying the wrong (root) redirect path must read as stale,
    # so sync refreshes it to the correct relative path.
    wrong_nested = (
        "# SuperCtx\n<!-- Generated by SuperCtx [DO NOT EDIT] -->\n\n"
        "Generated shim — do not edit. Edit `.ctx/SUPERCTX.md` instead.\n\n"
        "@../.ctx/SUPERCTX.md\n"
    )
    assert has_current_policy(wrong_nested, ".claude/CLAUDE.md") is False

    # A legacy shim with no redirect wording is stale.
    legacy = "# SuperCtx\n<!-- Generated by SuperCtx [DO NOT EDIT] -->\n@.ctx/SUPERCTX.md\n"
    assert has_current_policy(legacy, "CLAUDE.md") is False

def test_generate_shim_claude():
    # Root CLAUDE.md
    root_shim = generate_shim("CLAUDE.md", "claude-at-import")
    assert "<!-- Generated by SuperCtx [DO NOT EDIT] -->" in root_shim
    assert "@.ctx/SUPERCTX.md" in root_shim
    assert ".ctx/sources/CLAUDE.md" in root_shim
    # Verify backup reference is inside a comment and not active import
    assert "@.ctx/sources/CLAUDE.md" not in root_shim
    assert "<!--" in root_shim and ".ctx/sources/CLAUDE.md" in root_shim

    # Nested .claude/CLAUDE.md
    nested_shim = generate_shim(".claude/CLAUDE.md", "claude-at-import")
    assert "@../.ctx/SUPERCTX.md" in nested_shim
    assert "../.ctx/sources/.claude/CLAUDE.md" in nested_shim
    assert "@../.ctx/sources/.claude/CLAUDE.md" not in nested_shim

def test_generate_shim_plain():
    # Root AGENTS.md
    root_shim = generate_shim("AGENTS.md", "plain-pointer")
    assert "<!-- Generated by SuperCtx [DO NOT EDIT] -->" in root_shim
    assert "`.ctx/SUPERCTX.md`" in root_shim
    assert "`.ctx/sources/AGENTS.md`" in root_shim
    # Verify no active imports in plain pointer shim
    assert "@" not in root_shim

    # Nested .codex/AGENTS.md
    nested_shim = generate_shim(".codex/AGENTS.md", "plain-pointer")
    assert "`../.ctx/SUPERCTX.md`" in nested_shim
    assert "`../.ctx/sources/.codex/AGENTS.md`" in nested_shim
    assert "@" not in nested_shim

def test_apply_shim_new_file(tmp_path):
    # Applying to non-existent file
    res = apply_shim(tmp_path, "AGENTS.md")
    assert res["shimmed"] is True
    assert res["backed_up"] is False
    assert (tmp_path / "AGENTS.md").is_file()
    assert is_shim_file(tmp_path / "AGENTS.md")

def test_apply_shim_existing_file(tmp_path):
    make_repo(tmp_path, {"CLAUDE.md": "original content\n"})
    res = apply_shim(tmp_path, "CLAUDE.md")
    assert res["shimmed"] is True
    assert res["backed_up"] is True

    # Verify original is backed up
    backup = tmp_path / ".ctx" / "sources" / "CLAUDE.md"
    assert backup.is_file()
    assert backup.read_text(encoding="utf-8") == "original content\n"

    # Verify live is shimmed
    assert is_shim_file(tmp_path / "CLAUDE.md")

def test_apply_shim_already_shim(tmp_path):
    shim_text = "# SuperCtx\n<!-- Generated by SuperCtx [DO NOT EDIT] -->\n@.ctx/SUPERCTX.md\n<!-- Original pre-SuperCtx content backed up at:\n.ctx/sources/CLAUDE.md\n-->\n"
    make_repo(tmp_path, {
        "CLAUDE.md": shim_text,
        ".ctx/sources/CLAUDE.md": "true original content\n"
      })
    res = apply_shim(tmp_path, "CLAUDE.md")
    assert res["shimmed"] is True
    assert res["already_shim"] is True
    assert res["backed_up"] is False

    # Verify backup is NOT overwritten with the shim
    backup = tmp_path / ".ctx" / "sources" / "CLAUDE.md"
    assert backup.read_text(encoding="utf-8") == "true original content\n"

def test_apply_shim_backup_collision_prevention(tmp_path):
    make_repo(tmp_path, {
        "CLAUDE.md": "modified user content\n",
        ".ctx/sources/CLAUDE.md": "true original content\n"
      })
    # Apply shim without force — should REFUSE to shim and not modify files
    res = apply_shim(tmp_path, "CLAUDE.md", force_backup=False)
    assert res["shimmed"] is False
    assert res["reason"] == "backup_exists_and_live_has_edits"

    # Verify live content is preserved and backup is untouched
    assert (tmp_path / "CLAUDE.md").read_text(encoding="utf-8") == "modified user content\n"
    backup = tmp_path / ".ctx" / "sources" / "CLAUDE.md"
    assert backup.read_text(encoding="utf-8") == "true original content\n"

    # Apply shim WITH force — should overwrite backup and apply shim
    res2 = apply_shim(tmp_path, "CLAUDE.md", force_backup=True)
    assert res2["shimmed"] is True
    assert res2["backed_up"] is True
    assert backup.read_text(encoding="utf-8") == "modified user content\n"
    assert is_shim_file(tmp_path / "CLAUDE.md")

def test_apply_shim_already_shim_force_backup(tmp_path):
    # Proves we never back up an already generated shim even if force_backup is True
    shim_text = "# SuperCtx\n<!-- Generated by SuperCtx [DO NOT EDIT] -->\n@.ctx/SUPERCTX.md\n<!-- Original pre-SuperCtx content backed up at:\n.ctx/sources/CLAUDE.md\n-->\n"
    make_repo(tmp_path, {
        "CLAUDE.md": shim_text,
        ".ctx/sources/CLAUDE.md": "true original content\n"
      })
    res = apply_shim(tmp_path, "CLAUDE.md", force_backup=True)
    assert res["shimmed"] is True
    assert res["already_shim"] is True
    assert res["backed_up"] is False

    # Backup file must remain "true original content", not the shim text
    backup = tmp_path / ".ctx" / "sources" / "CLAUDE.md"
    assert backup.read_text(encoding="utf-8") == "true original content\n"

def test_sync_safety_with_shims(tmp_path):
    from superctx import init as init_cmd, sync as sync_cmd
    # 1. Initialize repository with CLAUDE.md
    make_repo(tmp_path, {"CLAUDE.md": "original content\n"})
    init_cmd.run(tmp_path)

    # 2. Verify original backup exists
    backup = tmp_path / ".ctx" / "sources" / "CLAUDE.md"
    assert backup.read_text(encoding="utf-8") == "original content\n"
    original_hub = core.hub_path(tmp_path).read_text(encoding="utf-8")

    # 3. Apply shim to CLAUDE.md (with force_backup=True since backup already exists from sync)
    res = apply_shim(tmp_path, "CLAUDE.md", force_backup=True)
    assert res["shimmed"] is True
    assert is_shim_file(tmp_path / "CLAUDE.md")

    # 4. Modify the backup content to simulate a distinguished original backup
    backup.write_text("distinguished original content\n", encoding="utf-8")

    # 5. Run sync command
    sync_res = sync_cmd.run(tmp_path)
    assert sync_res["mode"] == "healthy"
    assert sync_res["healthy"] == ["CLAUDE.md"]

    # 6. Verify backup is NOT overwritten with the shim content
    assert backup.read_text(encoding="utf-8") == "distinguished original content\n"

    # 7. Verify sync does not rebuild the hub from backups or shims
    hub = core.hub_path(tmp_path).read_text(encoding="utf-8")
    assert hub == original_hub
    assert "<!-- Generated by SuperCtx [DO NOT EDIT] -->" not in hub
