"""`superctx init` — scaffold the .ctx/ hub and auto-detect tracked tool files.

Idempotent and non-destructive: if .ctx/ already exists, it makes no changes.
"""

from __future__ import annotations

from pathlib import Path

from . import core, registry

_GITIGNORE_BODY = "# Raw per-tool snapshots are a local drift-detection cache.\nsources/\n"

_HUB_PLACEHOLDER = (
    "<!-- Generated by SuperCtx. Do not hand-edit — edit the tool files "
    "(CLAUDE.md, AGENTS.md, ...) and run /superctx:sync. -->\n\n"
    "# SUPERCTX\n\n"
    "This hub has not been populated yet. Run `/superctx:sync` to centralize the tracked "
    "tool instruction files into this file.\n"
)


def run(project_dir: Path) -> dict:
    project_dir = Path(project_dir)
    cdir = core.ctx_dir(project_dir)
    if cdir.exists():
        return {"created": False, "reason": "exists", "ctx_dir": str(cdir), "detected": []}

    discovery = registry.detect_all(project_dir)
    verified = discovery["verified_instruction_file"]
    core.sources_dir(project_dir).mkdir(parents=True, exist_ok=True)

    manifest = {
        "project": {
            "name": project_dir.resolve().name,
            "hub": f"{core.CTX_DIRNAME}/{core.HUB_NAME}",
        },
        "files": [{"path": c["path"], "tools": c.get("tools", [])} for c in verified],
    }
    core.manifest_path(project_dir).write_text(core.dump_manifest(manifest), encoding="utf-8")
    core.hub_path(project_dir).write_text(_HUB_PLACEHOLDER, encoding="utf-8")
    (cdir / ".gitignore").write_text(_GITIGNORE_BODY, encoding="utf-8")

    return {
        "created": True,
        "ctx_dir": str(cdir),
        "detected": [c["path"] for c in verified],
        "discovery": discovery,
    }
