from __future__ import annotations

import os
from pathlib import Path
from . import registry

WARNING_MARKER = "<!-- Generated by SuperCtx [DO NOT EDIT] -->"

def is_shim(content: str) -> bool:
    """Check if the content represents a valid SuperCtx shim."""
    normalized = content.replace("\r\n", "\n")
    return WARNING_MARKER in normalized and ".ctx/SUPERCTX.md" in normalized

def is_shim_file(path: Path) -> bool:
    """Check if the file at path is a valid SuperCtx shim."""
    if not path.is_file():
        return False
    try:
        content = path.read_text(encoding="utf-8")
        return is_shim(content)
    except Exception:
        return False

def generate_shim(rel_path: str, import_syntax: str) -> str:
    """Render the content of a shim for a given relative path and import syntax.
    
    Computes relative paths from the file's parent directory.
    """
    parent_dir = Path(rel_path).parent
    
    # Compute relative paths using forward slashes for cross-platform consistency
    rel_path_to_hub = os.path.relpath(".ctx/SUPERCTX.md", parent_dir).replace("\\", "/")
    rel_path_to_backup = os.path.relpath(f".ctx/sources/{rel_path}", parent_dir).replace("\\", "/")
    
    if import_syntax == "claude-at-import":
        return (
            f"# SuperCtx\n"
            f"{WARNING_MARKER}\n\n"
            f"@{rel_path_to_hub}\n\n"
            f"<!-- Original pre-SuperCtx content backed up at:\n"
            f"{rel_path_to_backup}\n"
            f"-->\n"
        )
    else:
        return (
            f"# SuperCtx\n"
            f"{WARNING_MARKER}\n\n"
            f"Use the shared project context in `{rel_path_to_hub}`.\n\n"
            f"Original pre-SuperCtx content is backed up at `{rel_path_to_backup}`.\n"
        )

def apply_shim(project_dir: Path, rel_path: str, force_backup: bool = False) -> dict:
    """Apply the shim to a live file in project_dir.
    
    1. Check if the live file exists.
    2. Check if the live file is already a shim.
    3. If not already a shim, and the live file exists, back it up to .ctx/sources/<rel_path>.
       If a backup already exists, refuse to modify unless force_backup=True.
    4. Render the shim content.
    5. Write the shim content to the live file.
    """
    project_dir = Path(project_dir)
    live_file = project_dir / rel_path
    backup_file = project_dir / ".ctx" / "sources" / rel_path
    
    # Determine import syntax from registry
    conv = registry.lookup_known_convention(rel_path)
    import_syntax = conv.get("import_syntax", "plain-pointer") if conv else "plain-pointer"
    
    live_exists = live_file.is_file()
    already_shim = False
    live_content = ""
    
    if live_exists:
        live_content = live_file.read_text(encoding="utf-8")
        already_shim = is_shim(live_content)
        
    backed_up = False
    if live_exists and not already_shim:
        backup_exists = backup_file.is_file()
        if backup_exists and not force_backup:
            return {
                "rel_path": rel_path,
                "shimmed": False,
                "reason": "backup_exists_and_live_has_edits",
                "already_shim": False,
                "backed_up": False,
                "backup_path": str(backup_file.relative_to(project_dir)),
            }
        
        # Perform backup
        backup_file.parent.mkdir(parents=True, exist_ok=True)
        backup_file.write_text(live_content, encoding="utf-8")
        backed_up = True
            
    shim_content = generate_shim(rel_path, import_syntax)
    live_file.parent.mkdir(parents=True, exist_ok=True)
    live_file.write_text(shim_content, encoding="utf-8")
    
    return {
        "rel_path": rel_path,
        "shimmed": True,
        "backed_up": backed_up,
        "backup_path": str(backup_file.relative_to(project_dir)) if (backed_up or backup_file.is_file()) else None,
        "already_shim": already_shim,
    }
