"""`superctx sync` — snapshot tracked tool files into .ctx/sources/ and regenerate SUPERCTX.md.

Inward only: tool files are read, never modified. SUPERCTX.md is a deterministic structured
aggregation, regenerated in full on every run.
"""

from __future__ import annotations

from pathlib import Path

from . import core

_BANNER = (
    "<!-- Generated by SuperCtx (/superctx:sync). Do not hand-edit — "
    "edit the tool files and re-run sync. -->\n"
)


def run(project_dir: Path) -> dict:
    project_dir = Path(project_dir)
    manifest = core.load_manifest(project_dir)
    centralized: list[str] = []
    missing: list[str] = []
    sections: list[str] = []

    for entry in manifest.get("files", []):
        rel = entry["path"]
        live = project_dir / rel
        if not live.is_file():
            missing.append(rel)
            continue

        text = core.read_text(live)
        snapshot = core.sources_dir(project_dir) / rel
        snapshot.parent.mkdir(parents=True, exist_ok=True)
        snapshot.write_text(text, encoding="utf-8")
        centralized.append(rel)

        tools = entry.get("tools", [])
        suffix = f"  ({', '.join(tools)})" if tools else ""
        sections.append(f"## From: {rel}{suffix}\n\n{text.strip()}\n")

    name = manifest.get("project", {}).get("name", "")
    body = "\n".join(sections) if sections else "_No tracked files found to centralize._\n"
    hub = f"{_BANNER}\n# SUPERCTX — {name}\n\n{body}"
    core.hub_path(project_dir).write_text(hub.rstrip() + "\n", encoding="utf-8")

    return {"centralized": centralized, "missing": missing}
